# Extend from Flutter's recommended lints
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.gr.dart"
    - "**/*.mocks.dart"
  errors:
    # Treat these warnings as errors
    dead_code: error
    unused_local_variable: error
    unused_import: error
    avoid_print: warning
    prefer_const_constructors: error

linter:
  rules:
    # ✅ Best Practices
    - avoid_classes_with_only_static_members
    - prefer_single_quotes
    - always_declare_return_types
    - avoid_dynamic_calls
    - prefer_final_fields
    - avoid_redundant_argument_values
    - prefer_relative_imports

    # 🎯 Style & Consistency
    - sort_constructors_first
    - curly_braces_in_flow_control_structures
    - prefer_expression_function_bodies
    - prefer_interpolation_to_compose_strings
    - omit_local_variable_types
    - require_trailing_commas
    - prefer_typing_uninitialized_variables

    # 💪 Safety & Performance
    - avoid_slow_async_io
    - close_sinks
    - cancel_subscriptions
    - avoid_returning_null_for_future
    - no_duplicate_case_values
    - use_function_type_syntax_for_parameters

    # 🧠 Naming Conventions
    - camel_case_types
    - camel_case_extensions
    - non_constant_identifier_names
    - library_prefixes
    - file_names

