name: lms1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  flex_color_scheme: ^8.2.0
  sizer: ^3.0.5
  fpdart: ^1.1.1
  go_router: ^14.8.1
  provider: ^6.1.4
  intl: ^0.20.2
  dio: ^5.8.0+1
  youtube_player_flutter: ^9.1.1
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon.png

  fonts:
     - family: Google
       fonts:
         - asset: assets/fonts/ProductSans-Light.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash.png"
  color_dark: "#000000"
  image_dark: "assets/images/splash_dark.png"
  android_12:
    image: "assets/images/splash.png"
    icon_background_color: "#FFFFFF"
    image_dark: "assets/images/splash_dark.png"
    icon_background_color_dark: "#000000"
  ios: true
  android: true